#! /bin/sh

# Setup up varying monitor resoultions by hostname
if [$HOSTNAME == "shibusa"]; then
  xrandr --output DP-4 --mode 3440x1440 --rate 100
elif [$HOSTNAME == "nanami"]; then
  xrandr --output DP-4 --mode 1920x1080 --rate 120
fi

# cleanup

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x alacritty > /dev/null || alacritty &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Alacritty border=off
bspc rule -a discord border=off
bspc rule -a firefox border=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
